#!/bin/sh
# Checks for PHP syntax errors and forbidden function calls

res=$(php -d display_errors=Off -d log_errors=On -l "$1" >&1)
if [ $? -ne 0 ]; then
    echo $res|grep 'Parse error'
fi

grep -Hn "\(var_dump\|print_r\|debug_print_backtrace\)" "$1";RET=$?
if [ $RET -ne 1 ]; then
    echo 'Forbidden function call found' 1>&2
fi
