#!/bin/sh
# Require a ticket number

grep -EHnq "[A-Z]+-[0-9]+" "$1"; RET=$?
if [ $RET -eq 0 ]; then
    exit 0
fi

grep -EHnq "^(Fixes|Resolves): \#[0-9]+" "$1"; RET=$?
if [ $RET -eq 0 ]; then
    exit 0
fi

echo "ERROR: Ticket number missing in commit message" 1>&2
exit 1
