#!/bin/sh
# Checks for PHP syntax errors and forbidden function calls

RES=$(php -d display_errors=Off -d log_errors=On -l "$1" 2>&1)
if [ $? -ne 0 ]; then
    echo 'Invalid PHP code found in' $1 1>&2
    echo $RES|grep --color=always '^PHP Parse error' 1>&2
    exit 1
fi

grep -Hn "\(var_dump\|print_r\|debug_print_backtrace\)" "$1"; RET=$?
if [ $RET -ne 1 ]; then
    echo 'Forbidden function call found' 1>&2
    exit 2
fi
